version: '3.8'

services:
  news:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parser_posts_tg_bot
    env_file:
      - .env
    volumes:
      - ./bot/sessions:/app/bot/sessions
      - ./img:/app/img
      - ./database:/app/database
    restart: unless-stopped
